<?php
/**
 * LindemannRock Formie Rating Field
 *
 * @link      https://lindemannrock.com
 * @copyright Copyright (c) 2026 LindemannRock
 */

declare(strict_types=1);

namespace lindemannrock\formieratingfield\tests\Support;

use craft\queue\Queue;
use Throwable;

/**
 * Hides the permanent Craft queue before enabled plugins bootstrap.
 *
 * @since 3.22.0
 */
final class IsolatedQueue extends Queue
{
    /** Exercise initialization cleanup after the shadow is installed. */
    public bool $failAfterShadowInstallation = false;

    private ?string $rawShadowTable = null;

    private ?string $rawStagingTable = null;

    public function init(): void
    {
        parent::init();

        try {
            if ($this->db->getDriverName() === 'mysql') {
                $this->rawShadowTable = $this->db->getSchema()->getRawTableName($this->tableName);
                $this->installMySqlShadow();
            } elseif ($this->db->getDriverName() === 'pgsql') {
                $this->installPostgresShadow();
            } else {
                throw new \RuntimeException('Formie Rating Field queue isolation supports MySQL and PostgreSQL.');
            }

            if ($this->failAfterShadowInstallation) {
                throw new \RuntimeException('Intentional queue-shadow initialization failure.');
            }
        } catch (Throwable $exception) {
            $this->dropTemporaryTable($this->rawStagingTable);
            $this->dropTemporaryTable($this->rawShadowTable);
            $this->rawStagingTable = null;
            $this->rawShadowTable = null;

            throw $exception;
        }

        register_shutdown_function(function(): void {
            try {
                $this->closeShadow();
            } catch (Throwable $exception) {
                fwrite(STDERR, 'Formie Rating Field queue-shadow cleanup failed: ' . $exception->getMessage() . PHP_EOL);
            }
        });
    }

    /** Remove only rows in the connection-local shadow queue. */
    public function clearShadowRows(): void
    {
        if ($this->rawShadowTable === null) {
            throw new \RuntimeException('The Formie Rating Field queue shadow is not active.');
        }

        $this->db->createCommand()->delete($this->tableName)->execute();
    }

    /** Drop only this connection's temporary queue relation. */
    public function closeShadow(): void
    {
        $this->dropTemporaryTable($this->rawShadowTable);
        $this->rawShadowTable = null;
    }

    private function installMySqlShadow(): void
    {
        $this->rawStagingTable = $this->rawShadowTable . '_formie_rating_test_' . bin2hex(random_bytes(8));
        $this->db->createCommand(sprintf(
            'CREATE TEMPORARY TABLE %s LIKE %s',
            $this->db->quoteTableName($this->rawStagingTable),
            $this->db->quoteTableName($this->rawShadowTable),
        ))->execute();
        $this->db->createCommand(sprintf(
            'ALTER TABLE %s RENAME TO %s',
            $this->db->quoteTableName($this->rawStagingTable),
            $this->db->quoteTableName($this->rawShadowTable),
        ))->execute();
        $this->rawStagingTable = null;
    }

    private function installPostgresShadow(): void
    {
        $tableSchema = $this->db->getTableSchema($this->tableName, true);
        if ($tableSchema === null) {
            throw new \RuntimeException('Unable to resolve Craft\'s permanent queue table.');
        }

        $this->rawShadowTable = $tableSchema->name;

        $this->db->createCommand(sprintf(
            'CREATE TEMPORARY TABLE %s (LIKE %s INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES) ON COMMIT PRESERVE ROWS',
            $this->db->quoteTableName($this->rawShadowTable),
            $this->db->quoteTableName($tableSchema->fullName),
        ))->execute();
        $this->db->createCommand(sprintf(
            'ALTER TABLE %s ALTER COLUMN [[id]] ADD GENERATED BY DEFAULT AS IDENTITY',
            $this->db->quoteTableName($this->rawShadowTable),
        ))->execute();

        $temporarySchema = $this->db->createCommand(<<<'SQL'
SELECT nspname
FROM pg_catalog.pg_namespace
WHERE oid = pg_catalog.pg_my_temp_schema()
SQL)->queryScalar();
        if (!is_string($temporarySchema) || $temporarySchema === '') {
            throw new \RuntimeException('Unable to resolve PostgreSQL\'s connection-local temporary schema.');
        }

        // Explicit temporary-schema qualification prevents a missing shadow
        // from resolving to the permanent queue, while letting Yii introspect
        // the binary job column and Craft resolve the temporary ID sequence.
        $this->tableName = $temporarySchema . '.' . $this->rawShadowTable;
    }

    private function dropTemporaryTable(?string $table): void
    {
        if ($table === null) {
            return;
        }

        if ($this->db->getDriverName() === 'mysql') {
            $this->db->createCommand(
                'DROP TEMPORARY TABLE IF EXISTS ' . $this->db->quoteTableName($table),
            )->execute();

            return;
        }

        if ($this->db->getDriverName() !== 'pgsql') {
            throw new \RuntimeException('Formie Rating Field queue cleanup supports MySQL and PostgreSQL.');
        }

        $temporaryRelationExists = (bool) $this->db->createCommand(<<<'SQL'
SELECT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_class
    WHERE relnamespace = pg_catalog.pg_my_temp_schema()
      AND relname = :relation
      AND relpersistence = 't'
      AND relkind IN ('r', 'p')
)
SQL, [':relation' => $table])->queryScalar();

        if (!$temporaryRelationExists) {
            return;
        }

        $this->db->createCommand(
            'DROP TABLE ' . $this->db->quoteTableName('pg_temp.' . $table),
        )->execute();
    }
}
